[package]
name = "xcmd_core"
version = "0.1.0"
authors = ["xcmd.io <developer@xcmd.io>"]
edition = "2018"

[dependencies]
sciter-rs = "*"
ssh2 = { git = "https://github.com/alexcrichton/ssh2-rs" }
owning_ref = "*"
derive_more = "0.99.2"
