	window-background = '#0000aa'
	window-foreground = '#54ffff'
	list-background = '#0000aa'
	list-headerBackground = '#0000aa'
	list-headerForeground = '#ffff57'
	list-headerBorder = '#0000aa'
	inactiveList-selectedForeground = '#ffff57'
	inactiveList-selectedBackground = '#0000aa'
	inactiveList-activeForeground = '#0000aa'
	inactiveList-activeBackground = '#00aaaa'
	inactiveList-selectedActiveForeground = '#ffff57'
	inactiveList-selectedActiveBackground = '#00aaaa'
	list-selectedForeground = '#ffff57'
	list-selectedBackground = '#0000aa'
	list-activeForeground = '#0000aa'
	list-activeBackground = '#00aaaa'
	list-selectedActiveForeground = '#ffff57'
	list-selectedActiveBackground = '#00aaaa'
	input-border = '#0000aa'
	input-background = '#0000aa'
	input-foreground = '#54ffff'
	input-focusBorder = '#0000aa'
	input-focusForeground = '#54ffff'
	input-focusBackground = '#0000aa'
	inactiveTab-foreground = '#0000aa'
	inactiveTab-background = '#00aaaa'
	tab-foreground = '#0000aa'
	tab-background = '#54ffff'
