window-background = '#252525'
window-foreground = '#b4b4b4'
list-background = '#1e1e1e'
list-headerBackground = '#2d2d2d'
list-headerForeground = '#949494'
list-headerBorder = '#3c3c3c'
inactiveList-selectedForeground = '#fff'
inactiveList-selectedBackground = '#37373d'
inactiveList-activeForeground = 'initial'
inactiveList-activeBackground = '#2a2d2e'
inactiveList-selectedActiveForeground = '#fff'
inactiveList-selectedActiveBackground = '#2a2d2e'
list-selectedForeground = '#fff'
list-selectedBackground = '#094771'
list-activeForeground = 'initial'
list-activeBackground = '#062f4a'
list-selectedActiveForeground = '#fff'
list-selectedActiveBackground = '#062f4a'
input-border = '#3c3c3c'
input-background = '#3c3c3c'
input-foreground = '#a6a6a6'
input-focusBorder = '#175b89'
input-focusForeground = '#fafafa'
input-focusBackground = '#3c3c3c'
inactiveTab-foreground = '#fff'
inactiveTab-background = '#3c3c3c'
tab-foreground = '#fff'
tab-background = '#007acc'
