	window-background = '#f3f3f3'
	window-foreground = '#6f6f6f'
	list-background = '#fff'
	list-headerBackground = '#ececec'
	list-headerForeground = '#6a6a6a'
	list-headerBorder = '#fff'
	inactiveList-selectedForeground = '#616161'
	inactiveList-selectedBackground = '#e4e6f1'
	inactiveList-activeForeground = '#616161'
	inactiveList-activeBackground = '#d8dae6'
	inactiveList-selectedActiveForeground = '#616161'
	inactiveList-selectedActiveBackground = '#d8dae6'
	list-selectedForeground = '#f9fbfe'
	list-selectedBackground = '#0069d1'
	list-activeForeground = '#616161'
	list-activeBackground = '#d6ebff'
	list-selectedActiveForeground = '#fff'
	list-selectedActiveBackground = '#0074e8'
	input-border = '#fff'
	input-background = '#fff'
	input-foreground = '#616161'
	input-focusBorder = '#99caeb'
	input-focusForeground = '#616161'
	input-focusBackground = '#fff'
	inactiveTab-foreground = '#616161'
	inactiveTab-background = '#dcdcdc'
	tab-foreground = '#fff'
	tab-background = '#007acc'
