22 = "backspace"
23 = "tab"
5 = "clear"
36 = "enter"
50 = "shift"
37 = "ctrl"
135 = "alt"
66 = "capslock"
9 = "escape"
65 = "space"
112 = "pageup"
117 = "pagedown"
115 = "end"
110 = "home"
113 = "left"
111 = "up"
114 = "right"
116 = "down"
107 = "printscreen"
118 = "insert"
119 = "delete"
19 = "0"
10 = "1"
11 = "2"
12 = "3"
13 = "4"
14 = "5"
15 = "6"
16 = "7"
17 = "8"
18 = "9"
38 = "a"
56 = "b"
54 = "c"
40 = "d"
26 = "e"
41 = "f"
42 = "g"
43 = "h"
31 = "i"
44 = "j"
45 = "k"
46 = "l"
58 = "m"
57 = "n"
32 = "o"
33 = "p"
24 = "q"
27 = "r"
39 = "s"
28 = "t"
30 = "u"
55 = "v"
25 = "w"
53 = "x"
29 = "y"
52 = "z"
90 = "numpad0"
87 = "numpad1"
88 = "numpad2"
89 = "numpad3"
83 = "numpad4"
84 = "numpad5"
85 = "numpad6"
79 = "numpad7"
80 = "numpad8"
81 = "numpad9"
63 = "numpadmultiply"
86 = "numpadadd"
104 = "numpadseparator"
82 = "numpadsubtract"
91 = "numpaddecimal"
106 = "numpaddivide"
67 = "f1"
68 = "f2"
69 = "f3"
70 = "f4"
71 = "f5"
72 = "f6"
73 = "f7"
74 = "f8"
75 = "f9"
76 = "f10"
95 = "f11"
96 = "f12"
47 = ";"
21 = "="
59 = ","
20 = "-"
60 = "."
61 = "/"
35 = "["
51 = "\\"
34 = "]"
48 = "'"
