8 = "backspace"
9 = "tab"
12 = "clear"
13 = "enter"
16 = "shift"
17 = "ctrl"
18 = "alt"
20 = "capslock"
27 = "escape"
32 = "space"
33 = "pageup"
34 = "pagedown"
35 = "end"
36 = "home"
37 = "left"
38 = "up"
39 = "right"
40 = "down"
41 = "select"
42 = "printscreen"
43 = "execute"
44 = "snapshot"
45 = "insert"
46 = "delete"
47 = "help"
48 = "0"
49 = "1"
50 = "2"
51 = "3"
52 = "4"
53 = "5"
54 = "6"
55 = "7"
56 = "8"
57 = "9"
65 = "a"
66 = "b"
67 = "c"
68 = "d"
69 = "e"
70 = "f"
71 = "g"
72 = "h"
73 = "i"
74 = "j"
75 = "k"
76 = "l"
77 = "m"
78 = "n"
79 = "o"
80 = "p"
81 = "q"
82 = "r"
83 = "s"
84 = "t"
85 = "u"
86 = "v"
87 = "w"
88 = "x"
89 = "y"
90 = "z"
93 = "contextmenu"
96 = "numpad0"
97 = "numpad1"
98 = "numpad2"
99 = "numpad3"
100 = "numpad4"
101 = "numpad5"
102 = "numpad6"
103 = "numpad7"
104 = "numpad8"
105 = "numpad9"
106 = "numpadmultiply"
107 = "numpadadd"
108 = "numpadseparator"
109 = "numpadsubtract"
110 = "numpaddecimal"
111 = "numpaddivide"
112 = "f1"
113 = "f2"
114 = "f3"
115 = "f4"
116 = "f5"
117 = "f6"
118 = "f7"
119 = "f8"
120 = "f9"
121 = "f10"
122 = "f11"
123 = "f12"
124 = "f13"
125 = "f14"
126 = "f15"
127 = "f16"
128 = "f17"
129 = "f18"
130 = "f19"
131 = "f20"
132 = "f21"
133 = "f22"
134 = "f23"
135 = "f24"
144 = "numlock"
145 = "scrolllock"
186 = ";"
187 = "="
188 = ","
189 = "-"
190 = "."
191 = "/"
192 = "`"
219 = "["
220 = "\\"
221 = "]"
222 = "'"
223 = "oem8"
226 = "oem102"
